/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cadastracliente.view;

import com.mycompany.cadastracliente.dao.ClienteDAO;
import com.mycompany.cadastracliente.dao.CriaBanco;
import com.mycompany.cadastracliente.dao.EnderecoDAO;
import com.mycompany.cadastracliente.model.Endereco;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gu5t4_B
 */
public final class TelaEnderecos extends javax.swing.JFrame {

    EnderecoDAO enderecoBanco = new EnderecoDAO(CriaBanco.conectarBanco());
    ClienteDAO clienteBanco = new ClienteDAO(CriaBanco.conectarBanco());
    
    /**
     * Creates new form TelaEnderecos
     */
    public TelaEnderecos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnderecos = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        txtFixoEnderecoPrincipal = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        btnAltera = new javax.swing.JButton();
        txtFixoEnderecoPrincipal1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEnderecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Endereço"
            }
        ));
        jScrollPane1.setViewportView(tblEnderecos);

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnInserir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        txtFixoEnderecoPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFixoEnderecoPrincipal.setText("Endereço Principal");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnAltera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAltera.setText("Alterar");
        btnAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraActionPerformed(evt);
            }
        });

        txtFixoEnderecoPrincipal1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFixoEnderecoPrincipal1.setText("<-----");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExcluir))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAltera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFixoEnderecoPrincipal1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFixoEnderecoPrincipal)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFixoEnderecoPrincipal)
                            .addComponent(txtFixoEnderecoPrincipal1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnAltera))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        voltarTela();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        excluiEndereco();
        todosOsEnderecosPorId();
        JOptionPane.showMessageDialog (null, "Endereço excluido.");
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        abrirTelaInserirEnderecos();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraActionPerformed
        // TODO add your handling code here:
        abrirTelaAlterarEnderecos();
    }//GEN-LAST:event_btnAlteraActionPerformed

    public void todosOsEnderecosPorId(){
        
        DefaultTableModel modelo = (DefaultTableModel) tblEnderecos.getModel();
        tblEnderecos.setRowSorter(new TableRowSorter(modelo));
        
        modelo.setRowCount(0);
        ArrayList<Endereco> listaClientePorId = enderecoBanco.pesquisaTodosEnderecosPorCpf(clienteBanco.pesquisaPorId(txtCpf.getText()));
        
        listaClientePorId.forEach(a -> {
            modelo.addRow(new Object[]{
                a.getEndereco(),
                a.getLogin()}
            );
        });
    }
    
    public void excluiEndereco(){
        int Linha = tblEnderecos.getSelectedRow();
        String endereco = tblEnderecos.getModel().getValueAt(Linha, 0).toString();
        enderecoBanco.excluirEndereco(endereco);
    }
    
    public void abrirTelaInserirEnderecos(){
        TelaIncluirEndereco telaIncluirEndereco = new TelaIncluirEndereco();
        telaIncluirEndereco.enviaCpf(this, txtCpf.getText());
        telaIncluirEndereco.enviaId(this, txtId.getText());
        telaIncluirEndereco.setVisible(true);
        this.dispose();
    }
    
    public void abrirTelaAlterarEnderecos(){
        int Linha = tblEnderecos.getSelectedRow();
        String endereco = tblEnderecos.getModel().getValueAt(Linha, 0).toString();
        TelaAlterarEndereco telaAlterarEndereco = new TelaAlterarEndereco();
        telaAlterarEndereco.enviaEndereco(this, endereco);
        telaAlterarEndereco.enviaCpf(this, txtCpf.getText());
        telaAlterarEndereco.enviaId(this, txtId.getText());
        telaAlterarEndereco.setVisible(true);
        this.dispose();
    }
    
    public void voltarTela(){
        TelaUsuario telaUsuario = new TelaUsuario();
        telaUsuario.enviaCpf(this, txtCpf.getText());
        telaUsuario.enviaId(this, txtId.getText());
        telaUsuario.setVisible(true);
        telaUsuario.todosOsClientesPorId();
        this.dispose();
    }
    
    public void enviaCpf(TelaIncluirEndereco enviado, String cpf){
        txtCpf.setText(cpf);
    }
    
    public void enviaId(TelaIncluirEndereco enviado, String id){
        txtId.setText(id);
    }
    
    public void enviaCpf(TelaUsuario enviado, String cpf){
        txtCpf.setText(cpf);
    }
    
    public void enviaId(TelaUsuario enviado, String id){
        txtId.setText(id);
    }
    
    public void enviaId(TelaAlterarEndereco enviado, String id){
        txtId.setText(id);
    }
    
    public void enviaCpf(TelaAlterarEndereco enviado, String cpf){
        txtCpf.setText(cpf);
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltera;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEnderecos;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JLabel txtFixoEnderecoPrincipal;
    private javax.swing.JLabel txtFixoEnderecoPrincipal1;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
