/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cadastracliente.view;

import com.mycompany.cadastracliente.dao.ClienteDAO;
import com.mycompany.cadastracliente.dao.CriaBanco;
import com.mycompany.cadastracliente.model.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author Gu5t4_B
 */
public class TelaIncluirClientes extends javax.swing.JFrame {

    ClienteDAO informacaoProcessada = new ClienteDAO(CriaBanco.conectarBanco());
    
    /**
     * Creates new form TelaIncluirClientes
     */
    public TelaIncluirClientes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFixoIncluirNome = new javax.swing.JLabel();
        txtFixoIncluirCpf = new javax.swing.JLabel();
        txtFixoIncluirRg = new javax.swing.JLabel();
        txtFixoIncluirEmail = new javax.swing.JLabel();
        txtFixoIncluirTelefone1 = new javax.swing.JLabel();
        txtFixoIncluirTelefone2 = new javax.swing.JLabel();
        txtFixoIncluirDataNascimento = new javax.swing.JLabel();
        txtIncluirDataNascimento = new com.toedter.calendar.JDateChooser();
        txtIncluirTelefone2 = new javax.swing.JTextField();
        txtIncluirTelefone1 = new javax.swing.JTextField();
        txtIncluirEmail = new javax.swing.JTextField();
        txtIncluirRg = new javax.swing.JTextField();
        txtIncluirCpf = new javax.swing.JTextField();
        txtIncluirNome = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFixoIncluirNome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtFixoIncluirNome.setText("Nome:");

        txtFixoIncluirCpf.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtFixoIncluirCpf.setText("CPF:");

        txtFixoIncluirRg.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtFixoIncluirRg.setText("RG:");

        txtFixoIncluirEmail.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtFixoIncluirEmail.setText("Email:");

        txtFixoIncluirTelefone1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtFixoIncluirTelefone1.setText("Telefone 1:");

        txtFixoIncluirTelefone2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtFixoIncluirTelefone2.setText("Telefone 2:");

        txtFixoIncluirDataNascimento.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtFixoIncluirDataNascimento.setText("Data de Nascimento:");

        btnIncluir.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFixoIncluirTelefone1)
                        .addGap(74, 74, 74)
                        .addComponent(txtIncluirTelefone1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFixoIncluirEmail)
                        .addGap(110, 110, 110)
                        .addComponent(txtIncluirEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFixoIncluirRg)
                        .addGap(127, 127, 127)
                        .addComponent(txtIncluirRg))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFixoIncluirCpf)
                        .addGap(122, 122, 122)
                        .addComponent(txtIncluirCpf))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFixoIncluirNome)
                        .addGap(105, 105, 105)
                        .addComponent(txtIncluirNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFixoIncluirDataNascimento)
                            .addComponent(txtFixoIncluirTelefone2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIncluirDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtIncluirTelefone2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFixoIncluirNome)
                    .addComponent(txtIncluirNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFixoIncluirCpf)
                    .addComponent(txtIncluirCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFixoIncluirRg)
                            .addComponent(txtIncluirRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFixoIncluirEmail)
                            .addComponent(txtIncluirEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFixoIncluirTelefone1)
                            .addComponent(txtIncluirTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFixoIncluirTelefone2)
                            .addComponent(txtIncluirTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFixoIncluirDataNascimento))
                    .addComponent(txtIncluirDataNascimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnVoltar))
                .addGap(3, 3, 3)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
        insereInformacao();
        voltaTela();
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        voltaTela();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void insereInformacao(){
        if (txtIncluirDataNascimento.getDate()== null){
            JOptionPane.showMessageDialog (null, "Não foi possivel prosseguir, informe uma data.");
            return;
        }
        Cliente inseriCliente = new Cliente();   
        inseriCliente.setNome(txtIncluirNome.getText());
        inseriCliente.setCpf(txtIncluirCpf.getText());
        inseriCliente.setRg(txtIncluirRg.getText());
        inseriCliente.setEmail(txtIncluirEmail.getText());
        inseriCliente.setTelefone1(txtIncluirTelefone1.getText());
        inseriCliente.setTelefone2(txtIncluirTelefone2.getText());
        inseriCliente.setDataNascimentoInserir(txtIncluirDataNascimento.getDate());
        inseriCliente.setAtivo(true);
        inseriCliente.setLogin(txtId.getText());

        informacaoProcessada.inseriCliente(inseriCliente);
    } 
    
    public void voltaTela(){
        TelaUsuario telaUsuario = new TelaUsuario();
        telaUsuario.enviaId(this, txtId.getText());
        telaUsuario.setVisible(true);
        telaUsuario.todosOsClientesPorId();
        this.dispose();
    }
    
    public void enviaId(TelaUsuario enviado, String nome){
        txtId.setText(nome);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel txtFixoIncluirCpf;
    private javax.swing.JLabel txtFixoIncluirDataNascimento;
    private javax.swing.JLabel txtFixoIncluirEmail;
    private javax.swing.JLabel txtFixoIncluirNome;
    private javax.swing.JLabel txtFixoIncluirRg;
    private javax.swing.JLabel txtFixoIncluirTelefone1;
    private javax.swing.JLabel txtFixoIncluirTelefone2;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIncluirCpf;
    private com.toedter.calendar.JDateChooser txtIncluirDataNascimento;
    private javax.swing.JTextField txtIncluirEmail;
    private javax.swing.JTextField txtIncluirNome;
    private javax.swing.JTextField txtIncluirRg;
    private javax.swing.JTextField txtIncluirTelefone1;
    private javax.swing.JTextField txtIncluirTelefone2;
    // End of variables declaration//GEN-END:variables
}
