/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cadastracliente.view;

import com.mycompany.cadastracliente.dao.ClienteDAO;
import com.mycompany.cadastracliente.dao.CriaBanco;
import com.mycompany.cadastracliente.model.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author Gu5t4_B
 */
public class TelaAlterarClienteAdm extends javax.swing.JFrame {

    ClienteDAO informacaoProcessada = new ClienteDAO(CriaBanco.conectarBanco());
    
    /**
     * Creates new form TelAlterarClienteAdm
     */
    public TelaAlterarClienteAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JLabel();
        txtCpf = new javax.swing.JLabel();
        txtRg = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtTelefone1 = new javax.swing.JLabel();
        txtTelefone2 = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JLabel();
        txtNovoTelefone2 = new javax.swing.JTextField();
        txtNovoTelefone1 = new javax.swing.JTextField();
        txtNovoEmail = new javax.swing.JTextField();
        txtNovoRg = new javax.swing.JTextField();
        txtNovoCpf = new javax.swing.JTextField();
        txtNovoNome = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtNovaDataNascimento = new com.toedter.calendar.JDateChooser();
        txtCpfAntigo = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtNome.setText("Nome:");

        txtCpf.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtCpf.setText("CPF:");

        txtRg.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtRg.setText("RG:");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtEmail.setText("Email");

        txtTelefone1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtTelefone1.setText("Telefone 1:");

        txtTelefone2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtTelefone2.setText("Telefone 2:");

        txtDataNascimento.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtDataNascimento.setText("Data de Nascimento:");

        btnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlterar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDataNascimento)
                        .addComponent(txtTelefone2)
                        .addComponent(txtTelefone1)
                        .addComponent(txtEmail)
                        .addComponent(txtRg)
                        .addComponent(txtCpf)
                        .addComponent(txtNome)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNovoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(txtNovoCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(txtNovoRg, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(txtNovoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(txtNovoTelefone1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(txtNovoTelefone2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(txtNovaDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(btnVoltar)
                        .addGap(70, 70, 70))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(txtCpfAntigo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome)
                    .addComponent(txtNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf)
                    .addComponent(txtNovoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRg)
                    .addComponent(txtNovoRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail)
                    .addComponent(txtNovoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone1)
                    .addComponent(txtNovoTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone2)
                    .addComponent(txtNovoTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDataNascimento)
                    .addComponent(txtNovaDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnVoltar))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfAntigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        alterCliente();
        botaoVoltar();
        JOptionPane.showMessageDialog (null, "Cliente alterado.");
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        botaoVoltar();
    }//GEN-LAST:event_btnVoltarActionPerformed

    public void alterCliente(){
        Cliente inserir = new Cliente();
        inserir.setNome(txtNovoNome.getText());
        inserir.setCpf(txtNovoCpf.getText());
        inserir.setRg(txtNovoRg.getText());
        inserir.setEmail(txtNovoEmail.getText());
        inserir.setTelefone1(txtNovoTelefone1.getText());
        inserir.setTelefone2(txtNovoTelefone2.getText());
        inserir.setDataNascimentoInserir(txtNovaDataNascimento.getDate());
        
        informacaoProcessada.alteraClienteAdm(inserir, txtCpfAntigo.getText());
    }
    
    public void botaoVoltar(){
        TelaClienteAdm telaClienteAdm = new TelaClienteAdm();
        telaClienteAdm.enviaLoginSenha(this, txtLogin.getText());
        telaClienteAdm.setVisible(true);
        telaClienteAdm.todosClientes();
        this.dispose();
    }
    
    public void enviaLoginSenha(TelaClienteAdm enviado, String login){
        txtCpfAntigo.setText(login);
    }
    
    public void enviaLogin(TelaClienteAdm eviado, String login){
        txtLogin.setText(login);
    }
    
    public void enviaInformacoes(TelaClienteAdm eviado, String Nome, String Cpf, String Rg, String Email, String Telefone1, String Telefone2){
        txtNovoNome.setText(Nome);
        txtNovoCpf.setText(Cpf);
        txtNovoRg.setText(Rg);
        txtNovoEmail.setText(Email);
        txtNovoTelefone1.setText(Telefone1);
        txtNovoTelefone2.setText(Telefone2);
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel txtCpf;
    private javax.swing.JTextField txtCpfAntigo;
    private javax.swing.JLabel txtDataNascimento;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JLabel txtNome;
    private com.toedter.calendar.JDateChooser txtNovaDataNascimento;
    private javax.swing.JTextField txtNovoCpf;
    private javax.swing.JTextField txtNovoEmail;
    private javax.swing.JTextField txtNovoNome;
    private javax.swing.JTextField txtNovoRg;
    private javax.swing.JTextField txtNovoTelefone1;
    private javax.swing.JTextField txtNovoTelefone2;
    private javax.swing.JLabel txtRg;
    private javax.swing.JLabel txtTelefone1;
    private javax.swing.JLabel txtTelefone2;
    // End of variables declaration//GEN-END:variables
}
