/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cadastracliente.view;

/**
 *
 * @author Gu5t4_B
 */
public class TelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdm
     */
    public TelaAdm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        btnCadastrarLogin = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnVisualizarLogins = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCadastrarLogin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCadastrarLogin.setText("Cadastrar Login");
        btnCadastrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLoginActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnVisualizarLogins.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnVisualizarLogins.setText("Visualizar Logins");
        btnVisualizarLogins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarLoginsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizarLogins, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnCadastrarLogin)
                .addGap(41, 41, 41)
                .addComponent(btnVisualizarLogins)
                .addGap(45, 45, 45)
                .addComponent(btnVoltar)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLoginActionPerformed
        // TODO add your handling code here:
        abrirCadastrarLogin();
    }//GEN-LAST:event_btnCadastrarLoginActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        botaoVolta();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVisualizarLoginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarLoginsActionPerformed
        // TODO add your handling code here:
        abrirVisualizarLogins();
    }//GEN-LAST:event_btnVisualizarLoginsActionPerformed

    public void abrirVisualizarLogins(){
        TelaLoginsAdm telaLogins = new TelaLoginsAdm();
        telaLogins.setVisible(true);
        this.dispose();
    }
    
    public void abrirCadastrarLogin(){
        TelaInterfaceCadastro interfaceCadastro = new TelaInterfaceCadastro();
        interfaceCadastro.setVisible(true);
        this.dispose();
    }
    
    public void botaoVolta(){
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
        this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarLogin;
    private javax.swing.JButton btnVisualizarLogins;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
