/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cadastracliente.view;

import com.mycompany.cadastracliente.dao.CriaBanco;
import com.mycompany.cadastracliente.dao.LoginDAO;
import com.mycompany.cadastracliente.model.Login;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gu5t4_B
 */
public final class TelaLoginsAdm extends javax.swing.JFrame {

    LoginDAO clienteBancoLogin = new LoginDAO(CriaBanco.conectarBanco());
    /**
     * Creates new form TelaLoginsAdm
     */
    public TelaLoginsAdm() {
        initComponents();
        todosLogins();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogins = new javax.swing.JTable();
        btnAltera = new javax.swing.JButton();
        btxVolta = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnAltera1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblLogins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Login", "Senha"
            }
        ));
        jScrollPane1.setViewportView(tblLogins);

        btnAltera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAltera.setText("Alterar");
        btnAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraActionPerformed(evt);
            }
        });

        btxVolta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btxVolta.setText("Volta");
        btxVolta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxVoltaActionPerformed(evt);
            }
        });

        btnCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCliente.setText("Clientes");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnAltera1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAltera1.setText("Excluir");
        btnAltera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltera1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnCliente)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAltera1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAltera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btxVolta)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltera)
                    .addComponent(btnCliente)
                    .addComponent(btxVolta))
                .addGap(18, 18, 18)
                .addComponent(btnAltera1)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraActionPerformed
         // TODO add your handling code here:
        alterarLogin();
    }//GEN-LAST:event_btnAlteraActionPerformed

    private void btxVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxVoltaActionPerformed
        // TODO add your handling code here:
        botaoVoltar();
    }//GEN-LAST:event_btxVoltaActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        cliente();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnAltera1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltera1ActionPerformed
        // TODO add your handling code here:
        deletaUsuarioLogin();
    }//GEN-LAST:event_btnAltera1ActionPerformed
   
    public void todosLogins(){
        DefaultTableModel modelo = (DefaultTableModel) tblLogins.getModel();
        tblLogins.setRowSorter(new TableRowSorter(modelo));
        
        modelo.setRowCount(0);
        ArrayList<Login> listaLogins = clienteBancoLogin.pesquisaTodosLogins();
        
        listaLogins.forEach(a -> {
            modelo.addRow(new Object[]{
                a.getUsuarioLogin(),
                a.getSenhaLogin()}
            );
        });
    }
    
    public void alterarLogin(){
        int Linha = tblLogins.getSelectedRow();
        String login = tblLogins.getModel().getValueAt(Linha, 0).toString();
        TelaAlterarLoginAdm alterarLoginAdm = new TelaAlterarLoginAdm();
        alterarLoginAdm.enviaLoginSenha(this, login);
        alterarLoginAdm.setVisible(true);
        this.dispose();
    }
    
     public void deletaUsuarioLogin(){
        int Linha = tblLogins.getSelectedRow();
        String login = tblLogins.getModel().getValueAt(Linha, 0).toString();
        clienteBancoLogin.excluirLogin(login);
        todosLogins();   
    }
    
    public void botaoVoltar(){
        TelaAdm telaAdm = new TelaAdm();
        telaAdm.setVisible(true);
        this.dispose();
    }
    
    public void cliente(){
        int Linha = tblLogins.getSelectedRow();
        String login = tblLogins.getModel().getValueAt(Linha, 0).toString();
        TelaClienteAdm telaClienteAdm = new TelaClienteAdm();
        telaClienteAdm.enviaLoginSenha(this, login);
        telaClienteAdm.setVisible(true);
        telaClienteAdm.todosClientes();
        this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltera;
    private javax.swing.JButton btnAltera1;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btxVolta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLogins;
    // End of variables declaration//GEN-END:variables
}
